export const TRANSACTION_UPDATE = 'TRANSACTION_UPDATE';
export const TRANSACTION_ERASE = 'TRANSACTION_ERASE';
export const TRANSACTION_ADD = 'TRANSACTION_ADD';
export const TRANSACTION_REINIT = 'TRANSACTION_REINIT';